### ISSUE TITLE
The bundle throws an exception when metadata contains full entity namespaces instead of the entity's alias

### ISSUE THREAD

**Issue by csarrazi** [alexandresalome/doctrine-extra-bundle#5] opened 2015-01-22 10:26 UTC
@alexandresalome, I'll describe this a little bit later (this week-end), as I have my hands full, right now! :)

**Comment by alexandresalome** [comment] 2015-01-22 13:05
OK but the description seems pretty clear :)

**Comment by csarrazi** [comment] 2015-01-22 13:47
Yeah, but I'll give you the exact line, stacktrace, etc. :)

**Comment by rjmunro** [comment] 2015-05-28 09:00
I think this is a duplicate of #2, fixed in #3.

**Closed** 2015-07-06 11:04 UTC

**Comment by csarrazi** [comment] 2015-07-06 11:33
Dont' really think so, because I still had an error when using FQCNs, and not entity aliases. Unless a new version has been tagged in-between. In this case, this could be solved by creating a new tag.

Btw, you up for :beers:, @alexandresalome, on 07/22 or 07/23? ;)
